version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./data/etl_db.sql:/docker-entrypoint-initdb.d/create_tables.sql

  python_script:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db
volumes:
  db:
    driver: local